name: Sync Fork

on:
  schedule:
    - cron: '0 */2 * * *' # Chạy tự động mỗi 2 tiếng một lần
  workflow_dispatch:      # Nút bấm chạy thủ công để test luôn

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # LƯU Ý: Chỉ điền "Username/RepoName", KHÔNG điền link https://
          upstream_repository: TienCE04/Nhom33_Chude9_CNWEB
          upstream_branch: main
          target_branch: main
          test_mode: false
